from pathlib import Path

from invoke import task

from fireball_sidecar_toolkit.check import check as toolkit_check
from fireball_sidecar_toolkit.mdfix import check_tree as md_check
from fireball_sidecar_toolkit.mdfix import fix_tree as md_fix

from . import docs, tests

# topics/**/AGENTS.md are generated by modules/toolkit/topic/templates.py (blank-after-header) —
# normalised by fixing that generator (the deferred /topic update), not by mdfix.
_MD_EXCLUDE = ("topics",)


@task
def fix(context, repo=None):
    """Run All Automated Fixes"""
    tests.style(context, fix=True, repo=repo)
    if repo:
        return
    docs.update_changelogs(context)
    changed = md_fix(Path.cwd(), write=True, exclude=_MD_EXCLUDE)
    print(f"Normalised {len(changed)} markdown file(s).")


@task
def test(context, repo=None):
    """Run All Tests"""
    tests.style(context, repo=repo)
    tests.unit(context, repo=repo)
    if repo:
        return
    toolkit_check(Path.cwd())  # sidecar.toolkit drift gate
    md_check(Path.cwd(), exclude=_MD_EXCLUDE)  # markdown house style — no blank after header, no stray ---
