"""Tests for modules.toolkit.setup.properties — scalar stamping, template-repo detection, .gitignore sync."""

import pytest
from modules.toolkit.setup import properties as setup_props

pytestmark = pytest.mark.setup


def _fresh_lines() -> list[str]:
    return setup_props._build_initial_content().splitlines(keepends=True)  # pylint: disable=protected-access


class TestReadScalar:
    """Tests for _read_scalar()."""

    def test_reads_value_inside_section(self):
        lines = _fresh_lines()
        value = setup_props._read_scalar(lines, "repo", "local")  # pylint: disable=protected-access
        assert value == "$HOME/path/to/this/repo"

    def test_missing_key_returns_none(self):
        lines = _fresh_lines()
        assert setup_props._read_scalar(lines, "repo", "nope") is None  # pylint: disable=protected-access

    def test_key_outside_section_not_matched(self):
        lines = _fresh_lines()
        assert setup_props._read_scalar(lines, "repos", "local") is None  # pylint: disable=protected-access


class TestReplaceScalar:
    """Tests for _replace_scalar()."""

    def test_replaces_value_inside_section(self):
        lines = _fresh_lines()
        assert setup_props._replace_scalar(lines, "repo", "local", "/abs/path")  # pylint: disable=protected-access
        assert setup_props._read_scalar(lines, "repo", "local") == "/abs/path"  # pylint: disable=protected-access

    def test_returns_false_for_missing_key(self):
        lines = _fresh_lines()
        assert not setup_props._replace_scalar(lines, "repo", "nope", "x")  # pylint: disable=protected-access


class TestIsTemplateRepo:
    """Tests for _is_template_repo()."""

    def test_template_remote_is_a_template(self):
        assert setup_props._is_template_repo("github.com/LevonBecker/template_python")  # pylint: disable=protected-access

    def test_real_repo_remote_is_not_a_template(self):
        assert not setup_props._is_template_repo("github.com/user/my_vault")  # pylint: disable=protected-access

    def test_falls_back_to_local_folder_name_when_no_remote(self, monkeypatch: pytest.MonkeyPatch):
        monkeypatch.setattr(setup_props, "_REPO_ROOT", setup_props._REPO_ROOT.parent / "template_shopify")  # pylint: disable=protected-access
        assert setup_props._is_template_repo(None)  # pylint: disable=protected-access


class TestSyncGitignoreTracking:
    """Tests for _sync_gitignore_tracking()."""

    _BLOCK = (
        "node_modules/\n"
        "\n"
        "# Machine-specific config — generated by `inv setup.properties` (see modules/setup/properties.py)\n"
        "/properties.yml\n"
        "\n"
        ".DS_Store\n"
    )

    def test_template_repo_leaves_gitignore_untouched(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text(self._BLOCK)
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/LevonBecker/template_python")  # pylint: disable=protected-access
        assert gitignore.read_text() == self._BLOCK

    def test_real_repo_strips_ignore_line_and_comment(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text(self._BLOCK)
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/user/my_vault")  # pylint: disable=protected-access
        content = gitignore.read_text()
        assert "/properties.yml" not in content
        assert "generated by `inv setup.properties`" not in content
        assert "\n\n\n" not in content
        assert "node_modules/" in content and ".DS_Store" in content

    def test_already_stripped_gitignore_is_idempotent(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text("node_modules/\n\n.DS_Store\n")
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/user/my_vault")  # pylint: disable=protected-access
        assert gitignore.read_text() == "node_modules/\n\n.DS_Store\n"


class TestBackfillMissingSections:
    """Tests for backfill_missing_sections() — adding tier-fragment sections to an existing file."""

    def _setup(self, tmp_path, monkeypatch, *, fragments: dict[str, str], existing: str) -> None:
        templates = tmp_path / "modules" / "setup" / "templates" / "properties"
        templates.mkdir(parents=True)
        for name, body in fragments.items():
            (templates / f"{name}.yml").write_text(body)
        props = tmp_path / "properties.yml"
        props.write_text(existing)
        monkeypatch.setattr(setup_props, "_TEMPLATES_DIR", templates)
        monkeypatch.setattr(setup_props, "_PROPERTIES_FILE", props)

    def test_adds_a_missing_section_and_leaves_existing_values_alone(self, tmp_path, monkeypatch):
        self._setup(
            tmp_path,
            monkeypatch,
            fragments={
                "template_python": 'repos:\n  acme:\n    - template_python\n\nrepo:\n  local: "x"\n',
                "acme_vault": 'screenshots:\n  location: "$HOME/shots"\n',
            },
            existing='---\n\nrepo:\n  local: "/real/path"\n',
        )
        added = setup_props.backfill_missing_sections()
        assert "screenshots" in added
        text = (tmp_path / "properties.yml").read_text()
        assert 'local: "/real/path"' in text  # untouched
        assert "screenshots:" in text and "$HOME/shots" in text

    def test_noop_when_every_section_is_present(self, tmp_path, monkeypatch):
        self._setup(
            tmp_path,
            monkeypatch,
            fragments={"template_python": 'repo:\n  local: "x"\n'},
            existing='---\n\nrepo:\n  local: "/real/path"\n',
        )
        assert setup_props.backfill_missing_sections() == []
