"""Tests for modules.setup.properties template-parent detection and stamping."""

import pytest

from modules.setup import properties as setup_props

pytestmark = pytest.mark.setup


def _template_lines() -> list[str]:
    return setup_props._build_initial_content().splitlines(keepends=True)  # pylint: disable=protected-access


def _stamp(lines, repo_local, monkeypatch, *, detected, confirm=False):
    monkeypatch.setattr(setup_props, "_detect_template_remote", lambda _remote: detected)
    monkeypatch.setattr(setup_props.cli, "confirm", lambda *_a, **_k: confirm)
    setup_props._stamp_template_parent(  # pylint: disable=protected-access
        lines, repo_local, "github.com/user/my_vault"
    )


class TestReadScalar:
    """Tests for _read_scalar()."""

    def test_reads_value_inside_section(self):
        lines = _template_lines()
        value = setup_props._read_scalar(lines, "template", "remote")  # pylint: disable=protected-access
        assert value == setup_props._TEMPLATE_REMOTE_PLACEHOLDER  # pylint: disable=protected-access

    def test_missing_key_returns_none(self):
        lines = _template_lines()
        assert setup_props._read_scalar(lines, "template", "nope") is None  # pylint: disable=protected-access

    def test_key_outside_section_not_matched(self):
        lines = _template_lines()
        assert setup_props._read_scalar(lines, "repos", "remote") is None  # pylint: disable=protected-access


class TestStampTemplateParent:
    """Tests for _stamp_template_parent()."""

    def test_detected_parent_stamped_with_sibling_local_guess(self, monkeypatch: pytest.MonkeyPatch):
        lines = _template_lines()
        _stamp(lines, "$HOME/Development/user/my_vault", monkeypatch, detected="github.com/user/template_my_vault")
        content = "".join(lines)
        assert 'remote: "github.com/user/template_my_vault"' in content
        assert 'local: "$HOME/Development/user/template_my_vault"' in content

    def test_hand_configured_parent_never_touched(self, monkeypatch: pytest.MonkeyPatch):
        lines = _template_lines()
        _stamp(lines, "$HOME/dev/my_vault", monkeypatch, detected="github.com/user/template_my_vault")
        before = "".join(lines)
        _stamp(lines, "$HOME/dev/my_vault", monkeypatch, detected="github.com/user/other_template")
        assert "".join(lines) == before

    def test_no_detection_and_declined_prompt_leaves_placeholder(self, monkeypatch: pytest.MonkeyPatch):
        lines = _template_lines()
        _stamp(lines, "$HOME/dev/my_vault", monkeypatch, detected=None, confirm=False)
        content = "".join(lines)
        assert setup_props._TEMPLATE_REMOTE_PLACEHOLDER in content  # pylint: disable=protected-access
        assert setup_props._TEMPLATE_LOCAL_PLACEHOLDER in content  # pylint: disable=protected-access

    def test_prompted_parent_stamped_when_confirmed(self, monkeypatch: pytest.MonkeyPatch):
        lines = _template_lines()
        monkeypatch.setattr(setup_props.cli, "prompt", lambda *_a, **_k: "github.com/user/template_my_vault")
        _stamp(lines, "$HOME/dev/my_vault", monkeypatch, detected=None, confirm=True)
        assert 'remote: "github.com/user/template_my_vault"' in "".join(lines)


class TestIsTemplateRepo:
    """Tests for _is_template_repo()."""

    def test_template_remote_is_a_template(self):
        assert setup_props._is_template_repo("github.com/LevonBecker/template_python")  # pylint: disable=protected-access

    def test_real_repo_remote_is_not_a_template(self):
        assert not setup_props._is_template_repo("github.com/user/my_vault")  # pylint: disable=protected-access

    def test_falls_back_to_local_folder_name_when_no_remote(self, monkeypatch: pytest.MonkeyPatch):
        monkeypatch.setattr(setup_props, "_REPO_ROOT", setup_props._REPO_ROOT.parent / "template_shopify")  # pylint: disable=protected-access
        assert setup_props._is_template_repo(None)  # pylint: disable=protected-access


class TestSyncGitignoreTracking:
    """Tests for _sync_gitignore_tracking()."""

    _BLOCK = (
        "node_modules/\n"
        "\n"
        "# Machine-specific config — generated by `inv setup.properties` (see modules/setup/properties.py)\n"
        "/properties.yml\n"
        "\n"
        ".DS_Store\n"
    )

    def test_template_repo_leaves_gitignore_untouched(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text(self._BLOCK)
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/LevonBecker/template_python")  # pylint: disable=protected-access
        assert gitignore.read_text() == self._BLOCK

    def test_real_repo_strips_ignore_line_and_comment(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text(self._BLOCK)
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/user/my_vault")  # pylint: disable=protected-access
        content = gitignore.read_text()
        assert "/properties.yml" not in content
        assert "generated by `inv setup.properties`" not in content
        assert "\n\n\n" not in content
        assert "node_modules/" in content and ".DS_Store" in content

    def test_already_stripped_gitignore_is_idempotent(self, tmp_path, monkeypatch: pytest.MonkeyPatch):
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text("node_modules/\n\n.DS_Store\n")
        monkeypatch.setattr(setup_props, "_REPO_ROOT", tmp_path)
        setup_props._sync_gitignore_tracking("github.com/user/my_vault")  # pylint: disable=protected-access
        assert gitignore.read_text() == "node_modules/\n\n.DS_Store\n"
