"""Per-tool renderers: each turns a :class:`~modules.devkit.content.ContentBundle` into the files
one AI tool expects inside a consuming repo.

A renderer is a callable ``render(bundle, repo_root) -> list[Path]`` that writes its outputs and
returns the paths it wrote (so :mod:`modules.devkit.render` and the drift check can diff them).
Every output file carries a ``DO NOT EDIT`` header — the canonical source is ``content/`` +
``_local/``.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from ..content import ContentBundle
from . import agents, claude, cline, copilot, opencode, prompts, sidecar

Renderer = Callable[[ContentBundle, Path], list[Path]]

# Order is irrelevant — every renderer owns a disjoint set of output paths.
ALL: dict[str, Renderer] = {
    "agents": agents.render,
    "claude": claude.render,
    "cline": cline.render,
    "copilot": copilot.render,
    "opencode": opencode.render,
    "prompts": prompts.render,
    "sidecar": sidecar.render,
}

GENERATED_HEADER = "<!-- DO NOT EDIT. Generated by ai_devkit from content/ + _local/. Run `invoke devkit.sync`. -->"
