"""Shared helpers for the per-tool renderers.

Every renderer writes markdown that starts with :data:`GENERATED_HEADER` and returns the paths it
wrote. :func:`write_doc` handles the header placement (after frontmatter, never before it — a
leading HTML comment would break frontmatter parsing). :func:`clean_dir` removes files a renderer
no longer produces so a dropped canonical slug's stale output disappears on the next render.

Every rendered provider file is a **pointer stub**: provider-specific frontmatter + the header +
one :func:`canonical_pointer` line back to ``ai/shared/`` or ``ai/local/``. No canonical body text
is ever inlined into generated output.
"""

from __future__ import annotations

import json
import re
import shutil
from collections.abc import Iterable, Mapping
from pathlib import Path

from ..catalog import Command, ContentBundle

GENERATED_HEADER = (
    "<!-- DO NOT EDIT. Generated by fireball_sidecar_toolkit from ai/shared/ + ai/local/. "
    "Run `invoke sidecar.toolkit.sync`. -->"
)


def canonical_pointer(bundle: ContentBundle, slug: str, kind: str) -> str:
    """The stub body pointing a provider file at its canonical source.

    ``kind`` is ``commands`` | ``instructions`` | ``skills``. Resolves to ``ai/local/`` when the
    slug came from the consuming repo's overlay, else ``ai/shared/``.
    """
    layer = "local" if bundle.is_local(slug) else "shared"
    return f"Source of truth: `ai/{layer}/{kind}/{slug}.md`"


_YAML_UNSAFE = re.compile(r"(^[\s>@`|*&!%#\"'\[{-])|(:\s)|(\s#)|(^$)")


def _scalar(value: str) -> str:
    """Render a string as a YAML scalar, double-quoting only when a bare scalar would be unsafe."""
    return json.dumps(value) if _YAML_UNSAFE.search(value) else value


def render_frontmatter(fields: Mapping[str, object]) -> str:
    """A deterministic YAML frontmatter block (no surrounding ``---``). Keys keep insertion order.

    ``str`` values are bare unless unsafe; ``list``/``tuple`` values become block sequences; empty
    values are skipped entirely.
    """
    lines: list[str] = []
    for key, value in fields.items():
        if value in (None, "", (), []):
            continue
        if isinstance(value, (list, tuple)):
            lines.append(f"{key}:")
            lines.extend(f"  - {_scalar(str(item))}" for item in value)
        else:
            lines.append(f"{key}: {_scalar(str(value))}")
    return "\n".join(lines)


def write_doc(path: Path, body: str, *, frontmatter: Mapping[str, object] | None = None) -> Path:
    """Write ``path`` with the generated header, optional frontmatter, and ``body``. Returns ``path``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = []
    if frontmatter:
        block = render_frontmatter(frontmatter)
        if block:
            parts.append(f"---\n{block}\n---\n")
    parts.append(GENERATED_HEADER)
    parts.append("")
    parts.append(body.strip() + "\n")
    path.write_text("\n".join(parts), encoding="utf-8")
    return path


def clean_dir(directory: Path, keep: Iterable[Path], *, suffix: str = ".md") -> None:
    """Delete ``*<suffix>`` files under ``directory`` that are not in ``keep``. No-op if absent."""
    if not directory.is_dir():
        return
    keep_set = {p.resolve() for p in keep}
    for path in directory.rglob(f"*{suffix}"):
        if path.resolve() not in keep_set:
            path.unlink()


def clean_subdirs(parent: Path, keep_names: Iterable[str]) -> None:
    """Remove immediate child directories of ``parent`` whose name is not in ``keep_names``."""
    if not parent.is_dir():
        return
    keep = set(keep_names)
    for child in parent.iterdir():
        if child.is_dir() and child.name not in keep:
            shutil.rmtree(child)


_AWS_PREFIX = re.compile(r"^(AWS_PROFILE=\S+) uv run")


def derive_allowed_tools(command: Command) -> list[str]:
    """The Claude Code ``allowed-tools`` globs for a command.

    Explicit canonical ``allowed-tools`` frontmatter wins. Otherwise derive from the body's
    ``!`...``` exec lines: ``uv run --no-sync …`` → ``Bash(uv run --no-sync *)``,
    ``AWS_PROFILE=X uv run …`` → that plus the bare ``uv run`` glob, ``./setup.sh`` →
    ``Bash(./setup.sh)``. No exec line → no entry (the command is prose-only).
    """
    if command.allowed_tools:
        return list(command.allowed_tools)
    tools: list[str] = []
    for line in command.exec_lines:
        if line.startswith("./setup.sh"):
            _add(tools, "Bash(./setup.sh)")
        elif match := _AWS_PREFIX.match(line):
            _add(tools, f"Bash({match.group(1)} uv run --no-sync *)")
            _add(tools, "Bash(uv run --no-sync *)")
        elif line.startswith("uv run"):
            _add(tools, "Bash(uv run --no-sync *)")
    return tools


def _add(items: list[str], value: str) -> None:
    if value not in items:
        items.append(value)
